services:
  - type: web
    name: flask-board
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    branches:
      - main
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    runtime: python3.9
    routes:
      - path: /
        type: static
        url: /static
